apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - args:
        - --logpath=/dev/null
        image: mongo:4
        name: kamel-mongodb
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: database-claim0
      restartPolicy: Always
      volumes:
      - name: database-claim0
        persistentVolumeClaim:
          claimName: database-claim0
status: {}
