version: '3'
services:
  frontend:
    build: ./client
    ports:
      - '3000:80'
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - kamel
  backend:
    build: ./backend
    depends_on:
      - database
    networks:
      - kamel
  database:
    image: mongo:4
    container_name: 'kamel-mongodb'
    volumes:
      - ./data/db:/data/db
    command: --logpath=/dev/null
    networks:
      - kamel
networks:
  kamel:
    driver: bridge